updated yml

diff --git a/.github/workflows/dotnet-code-coverage.yml b/.github/workflows/dotnet-code-coverage.yml
--- a/.github/workflows/dotnet-code-coverage.yml
+++ b/.github/workflows/dotnet-code-coverage.yml
@@ -39,6 +39,10 @@ jobs:
           coverage=$(grep -oP '(?<=line-rate=\")[^\"]+' "$coverage_file" | awk '{total += $1; count++} END {print total/count}')
           echo "Coverage: $coverage"
           echo "COVERAGE_VALUE=$coverage" >> $GITHUB_ENV
+          if (( $(echo "$coverage < 0.80" | bc -l) )); then
+            echo "Code coverage is below 80%. Failing the build."
+            exit 1
+          fi
         else
           echo "Coverage file not found. Failing the build."
           exit 1
