updated yml

diff --git a/.github/workflows/dotnet-code-coverage.yml b/.github/workflows/dotnet-code-coverage.yml
--- a/.github/workflows/dotnet-code-coverage.yml
+++ b/.github/workflows/dotnet-code-coverage.yml
@@ -35,13 +35,26 @@ jobs:
         dotnet test --no-restore --collect:"XPlat Code Coverage" \
         /p:CoverletOutputFormat=cobertura
 
+    - name: List coverage report files
+      run: ls -R coveragereport
+
     - name: Generate and check coverage report
       run: |
         reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport
-        coverage=$(grep -oP '(?<=line-rate=\")[^\"]+' coveragereport/cobertura.xml | awk '{total += $1; count++} END {print total/count}')
-        echo "Coverage: $coverage"
-        if (( $(echo "$coverage < 0.80" | bc -l) )); then
-          echo "Code coverage is below 80%. Failing the build."
+        if [ -f coveragereport/cobertura/cobertura.xml ]; then
+          coverage=$(grep -oP '(?<=line-rate=\")[^\"]+' coveragereport/cobertura/cobertura.xml | awk '{total += $1; count++} END {print total/count}')
+          if [ -z "$coverage" ]; then
+            echo "No coverage data found."
+            exit 1
+          else
+            echo "Coverage: $coverage"
+            if (( $(echo "$coverage < 0.80" | bc -l) )); then
+              echo "Code coverage is below 80%. Failing the build."
+              exit 1
+            fi
+          fi
+        else
+          echo "Coverage file not found. Failing the build."
           exit 1
         fi
 
